### ISSUE TITLE
Power Supply Clarification

### ISSUE THREAD

**Issue by GaganBhat** [mahirgul/wifi-nodemcu-robot-esp8266#2]
Hi, thanks for putting together this great niche guide!

According to the figure in the readme, I see that you have a wire going from VIN of NodeMCU to the +M of the adafruit board.

<img width="811" alt="image" src="https://user-images.githubusercontent.com/25236969/209890501-3e97780f-d1f3-4e2e-9a57-df3ce1010b5f.png">

This is confusing because I'm not sure where the external power source for this is. How is the Adafruit Motor Shield getting power in order to also power the NodeMCU?

Is this not shown on the diagram?

**Comment by mahirgul** [comment]
![IMG-20221229-WA0000](https://user-images.githubusercontent.com/8502843/209890827-b47b868f-1da1-440b-bdd6-cc255c5b8d8e.jpg)
I supply voltage from the socket on the adafruit board.
jumper must be installed

**Comment by GaganBhat** [comment]
That makes sense, thanks!

**Comment by GaganBhat** [comment]
@mahirgul One additional question, why are we connecting +M to 5V of the same adafruit board? Similarly, is the connection from GND to port 7 required?

**Comment by GaganBhat** [comment]
Following up -- Port 7 on the Motor Shield should be set to LOW explicitly, as it is the enable pin for the motors. This is what I was missing. The motor shield control works now, thanks!

**Comment by mahirgul** [comment]
👍
